### ISSUE TITLE
Create an Empathy Map for Customer : Cold Calling Recipients

### ISSUE THREAD

**Issue by Jyuston** [kelvin-weng/ISDM-Tutorial-7-Group-7#4]
Customer's who are cold called will have a different experience with the Travel Company.

**Comment by Astra-8** [comment]
Started a new lucidchart empathy map for stakeholder: outbound called customers and inbound calling customers

**Comment by Astra-8** [comment]
Revise customer stakeholder based on tutor review:
Customers being called by RM
Customers calling the travel company

**Comment by Astra-8** [comment]
Completed the empathy map and added POV statement
